spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/my-app-realm
          jwk-set-uri: http://localhost:8080/realms/my-app-realm/protocol/openid-connect/certs
  liquibase:
    change-log: "classpath:/db/master.xml"
    drop-first: false
  datasource:
    url: jdbc:postgresql://localhost:5432/appdb
    username: appuser
    password: appsecret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  port: 8081


